name: Deploy Oshi Chan
on:
  push:
    branches:
      - main
jobs:
  deploy-oshi-chan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo ${{ github.actor }}
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --config ./oshi-chan/fly.toml --dockerfile ./oshi-chan/Dockerfile
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}